export const dados = {
    'Verdade' : {
        'Infantil' : [
            "Qual foi o seu último sonho?",
            "Você já matou aula?",
            "Você já mentiu sobre a sua idade?",
            "Você já quebrou alguma coisa e não contou a ninguém?",
            "Quais plantas você teria em seu jardim?",
            "Você já espionou seu irmão?",
            "Quando você usou o fio dental pela última vez?",
            "Você tem uma queda por alguém?",
            "Qual foi o presente menos favorito que você já recebeu?",
            "Qual é a coisa mais irritante da terra para você?",
            "Você já vomitou em uma montanha-russa?",
            "Você já mentiu para um professor e sobre o que era?",
            "Qual é o seu vegetal favorito?",
            "Qual foi o melhor dia da sua vida?",
            "Quantos membros da família?",
            "Se você tivesse 1 minuto para sair de sua casa, o que pegaria?",
            "Existe uma bagunça no seu armário?",
            "Você tem uma queda por alguém? Nomeie-o!",
            "Se você pudesse escolher seu nome, qual seria?",
            "O que você mudaria sobre si mesmo?",
            "Você já mentiu sobre a sua idade?",
            "Em que algo você gostaria que fosse melhor?",
            "Você tem uma queda por alguém?",
            "Você prefere chocolate ou baunilha?",
            "Qual é o sonho mais estranho que você já teve?",
            "Qual é a sua posição favorita para dormir?",
            "Quantas cópias do Reader's Digest você já viu?",
            "Você chorou em público?",
            "Você já disse aos seus avós que os odiava?",
            "Qual foi o seu último sonho?",
            "Quando foi a última vez que você fez algo legal por outra pessoa?",
            "Se você pudesse ter alguma coisa no mundo, o que seria?",
            "Qual é a sua superpotência secreta?",
            "Quando foi a última vez que seu quarto viu um vácuo?",
            "Você ignora seus pais?",
            "Você rouba lanches quando ninguém está olhando?",
            "você já roubou alguma coisa?",
            "Se você pudesse pintar seu quarto de qualquer cor, o que escolheria?",
            "Quem é o seu super-heroi favorito?",
            "Você já traiu um teste?",
            "Quem você quer ser quando crescer?",
            "Você assistiu um filme de terror sozinho?",
            "Qual é a sua posição favorita para dormir?",
            "O que te faz feliz?",
            "O que você mais gosta em todos na sala?",
            "Você prefere ter um animal de estimação ou um irmão?",
            "Existe algo que você mudaria sobre si mesmo?",
            "Se você tivesse uma máquina do tempo, que período visitaria?",
            "Você tem uma queda por alguém?",
            "Você já foi a um zoológico?",
            "Qual é o seu pior hábito?",
            "Qual é o seu mau hábito?",
            "Você tem uma queda por alguém? Nomeie-o!",
            "Você ama mais sua mãe ou pai?",
            "Você prefere chocolate ou baunilha?",
            "Você foi acampar no seu quintal?",
            "Quantos membros da família?",
            "Você roubou dinheiro de seus pais?",
            "Você já deu seus vegetais ao cachorro?",
            "Você já lambeu seu prato antes?",
            "Você pega seu nariz?",
            "Você peidou em público?",
            "Quando foi a última vez que você fez algo legal por outra pessoa?",
            "Qual foi o seu último sonho?",
            "Você prefere ser uma princesa ou uma sereia?",
            "Qual é o seu vegetal favorito?",
            "Você já mentiu para um professor e sobre o que era?",
            "Você já usou dinheiro do almoço em algo que não deveria?",
            "O que faz você relaxar?",
            "Qual é o seu pior hábito?",
            "Você já esteve em um trem?",
            "Qual é a sua refeição favorita?",
            "Quando foi a última vez que seu quarto viu um vácuo?",
            "Você já tocou em uma vaca antes?",
            "Quais são algumas das maneiras pelas quais você trapaceia?",
            "Qual a coisa mais embaraçosa que você usou na escola?",
            "Qual foi a coisa mais idiota que você já fez com alguém que você gostou?",
            "Existe algo em que você se arrependeu de gastar dinheiro?",
            "Você gosta de dançar ou cantar?",
            "O que você quer ser quando crescer?",
            "O que você mais gosta em todos na sala?",
            "Qual é o seu sanduíche favorito?",
            "Você pode falar em diferentes idiomas?",
            "Você peidou em público?",
            "Você já deu comida a um sem-teto?",
            "Quando foi a última vez que você fez algo legal por outra pessoa?",
            "Você é uma pessoa da manhã ou da noite?",
            "Quando é a última vez que você se desculpou sinceramente?",
            "Qual foi o seu momento mais embaraçoso de peido?",
            "Você já lambeu seu prato antes?",
        ],
        'Clássico' : [
            "Você teria um encontro com alguém do mesmo sexo? ",
            "Você já cantou e dançou no supermercado? ",
            "Você ainda dorme com um ursinho de pelúcia? ",
            "Você já morou com alguém? ",
            "Com quantas pessoas você já dormiu? ",
            "Qual foi a coisa mais louca que você já fez nua? ",
            "Qual é o pior emprego que você poderia ter? ",
            "Se você tivesse que escolher um novo nome, qual você escolheria? ",
            "Com quem você escolheria trocar sua namorada / namorado se tivesse que escolher? ",
            "Qual foi a coisa mais embaraçosa que você fez até agora?",
            "Qual é a sua maior irritação? ",
            "Se você pudesse ficar invisível, o que faria? ",
            "Você já manteve uma resolução de ano novo? Se sim, qual (s)? ",
            "Do que você tem medo? ",
            "Qual é a situação mais embaraçosa em que você já peidou? ",
            "Você já foi infiel ao seu namorado / namorada? ",
            "Se você tivesse que renomear um nome que não fosse o seu, qual você escolheria? ",
            "Qual é o melhor prato que sua mãe faz para o jantar? ",
            "Quem é a pessoa mais bonita da sala? ",
            "Você passaria pelas costas de um amigo com uma queda? ",
            "Qual animal mais se assemelha à sua personalidade? ",
            "Deseja mudar seu primeiro nome? Se sim, qual seria? ",
            "Você já fez xixi na piscina?",
            "Você pode tocar sua língua no nariz? ",
            "Qual é a melhor parte de ter / não ter irmãos? ",
            "Qual é a pior comida que você já comeu? ",
            "Você prefere apple ou android? ",
            "Qual é a coisa mais doce que alguém do sexo oposto já fez por você?",
            "Você já viu um fantasma? ",
            "Com quem nesta sala você ficaria mais feliz em compartilhar um saco de dormir? ",
            "Que tipo de delícia deliciosa te excita? ",
            "Se você tivesse que escrever um artigo sobre seu herói pessoal, quem seria?",
            "Qual é a linha de coleta mais louca que você já ouviu? ",
            "Quem é a pessoa mais gostosa no trabalho ou na escola? ",
            "Você já teve um amigo imaginário? Se sim, qual era o nome deles?",
            "Se você está sendo honesto, qual é a sua maior falha? ",
            "Você já teve uma queda por alguém que seu melhor amigo namorou? ",
            "Se você fosse um rei do seu próprio reino, qual seria sua primeira ordem? ",
            "O que você gosta de fazer em um dia chuvoso?",
            "Quem na sala você acha que seria um encontro ruim? ",
            "Você gosta de se exercitar? ",
            "Qual foi a coisa mais louca que você já fez em sua vida até agora? ",
            "Você conhece a letra de todo o hino nacional? ",
            "Quais foram suas primeiras impressões sobre mim (a pessoa que fez a pergunta)? ",
            "Você já usou as mesmas roupas por mais de três dias? ",
            "Você já trapaceou para ganhar um jogo? ",
            "Você poderia passar uma semana sem junk food? ",
            "Você já esteve em um flash mob? ",
            "Se você pudesse ser qualquer super vilão, quem seria? ",
            "Qual é o vídeo mais engraçado do youtube que você já viu?",
            "Qual é a pior comida que você já comeu? ",
            "O pensamento de beijar a pessoa à sua esquerda o excita? ",
            "Qual é a única coisa da qual você tem mais vergonha? ",
            "Qual é a sua coisa favorita sobre o sexo oposto? ",
            "Você prefere ser inteligente ou feliz e por quê? ",
            "Você já tirou dinheiro do seu companheiro de quarto? ",
            "Qual é a sua piada favorita? ",
            "Quais são as suas três cores favoritas e por quê? ",
            "Qual foi o tempo mais longo que você já ficou de castigo? ",
            "Qual foi o maior erro que você já cometeu? ",
            "Descreva a casa dos seus sonhos ",
            "Quantos filhos você gostaria de ter? ",
            "Existem regras ou normas sociais que o irritam? ",
            "Qual é seu programa de TV favorito? ",
            "Se você estivesse preso em uma ilha, quem seria a única pessoa que você gostaria de ficar com você? ",
            "Se você estivesse preso em uma ilha por 3 dias, o que levaria com você?",
            "Qual a cor da sua calcinha? ",
            "Você acredita em fantasmas? Se sim, você está com medo deles? ",
            "Se sua vida fosse transformada em filme, qual ator / atriz interpretaria você? ",
            "Qual foi o último livro que você leu? ",
            "Quanto tempo você fica sem dormir? ",
            "Se você pudesse ter qualquer coisa no mundo, o que seria? ",
            "Você já disse algo ruim sobre alguém nesta sala? ",
            "Com o que você sonha mais? ",
            "O que você faria com um milhão de dólares se ganhasse na loteria? ",
            "Aponte para a pessoa com maior probabilidade de roubar sua comida quando você não estiver olhando. ",
            "Aponte para duas pessoas na sala com maior probabilidade de se beijar até o final da noite. ",
            "Você já foi demitido de um emprego? Por quê? ",
            "Quem é o melhor colega de quarto que você já teve? ",
            "Qual é a pior coisa de ser do seu sexo? ",
            "Você acha que a Terra é o único planeta habitável? Você acredita em alienígenas? ",
            "Você prefere ser um porco ou cobra? ",
            "O que você prefere: estar junto com alguém que você não ama ou estar com alguém que não te ama de volta? ",
            "Qual é o seu maior medo? ",
            "Você já flertou em uma festa?",
            "Há quanto tempo você fica sem tomar banho? ",
            "Com quem nesta sala seria o pior a ser preso em um elevador? ",
            "Conte-nos uma história bêbada sua. ",
            "Qual é a sua fantasia secreta? ",
            "O pensamento de beijar a pessoa à sua direita te excita? ",
            "O que você faria se seu atual namorado / namorada terminasse as coisas agora? ",
            "Gostosa ou não: piercings no umbigo? ",
            "Onde você estava durante o seu primeiro beijo? ",
            "Qual foi a brincadeira mais desagradável que você já fez em alguém? ",
            "Quem você tem no seu bloco do Facebook ou lista limitada? ",
            "Você já mentiu para seus pais se estava ou não nas aulas? ",
            "Você escolhe crostas? ",
            "Que ação do seu passado o colocaria na prisão se a polícia descobrisse isso? ",
            "Qual é o seu desenho animado favorito da sua geração? ",
        ],
        'Adulto' : [
            "Você já fez ménage?",
            "Você já traiu?",
            "Qual é o sonho sexual mais quente que você já teve?",
            "Diga ao seu parceiro como criar uma atmosfera sexual e romântica",
            "Você faria sexo para obter vantagens no trabalho?",
            "Quanto tempo dura a sua rapidinha ideal?",
            "Quando foi a última vez que você transou?",
            "Você já foi masturbado(a) no trabalho?",
            "Você prefere sexo com brincadeiras ou sensual?",
            "O que mais te excita: assistir pornografia ou gravar uma fita de sexo?",
            "Quantos parceiros sexuais você tinha até agora?",
            "Quem é a pessoa de quem você mais se arrepende de beijar?",
            "Se fôssemos fazer um filme sexy, qual seria o título?",
            "Qual é a sua memória mais romântica?",
            "Você prefere namorar alguém mais novo ou mais velho que você?",
            "Depois de quantas datas você costuma fazer sexo?",
            "Você prefere brincadeiras onde rimos muito ou sexo apaixonado onde somos muito sensuais?",
            "Por que você terminou com seu último namorado ou namorada?",
            "Qual é a sua maior desativação em seu parceiro atual (ou a última, se você não tem uma corrente)?",
            "Qual é a sua parte do corpo favorita em si mesmo? No seu parceiro?",
            "Qual foi a sua melhor experiência sexual?",
            "Você é mais dominante ou submisso?",
            "Você gosta mais quando uso minhas mãos ou meus lábios quando lhe agrada?",
            "Você já pensou em fazer sexo a três?",
            "Qual é a sua música sexual favorita?",
            "Você já teve uma queda pelo mesmo sexo?",
            "Diga-me uma coisa que eu poderia fazer que faria você imediatamente ter um orgasmo.",
            "Você prefere ter música em segundo plano ou ficar quieta?",
            "Que movimento de colchão meu é o seu favorito? Dê-me todos os detalhes sujos sobre por que você gosta.",
            "Qual é o seu tipo de sexo favorito? É macio e doce ou agressivo e travesso?",
            "Você já fez sexo com alguém do mesmo sexo?",
            "Qual foi a coisa mais estranha que já te excitou?",
            "Quando foi sua maior noite de bebedeira?",
            "Qual é o lugar mais incomum onde você fez sexo?",
            "Você prefere fazer sexo na máquina de lavar ou no capô de um carro?",
            "Quem foi seu melhor parceiro e por quê?",
            "Você se apaixonou por um amigo do seu parceiro? Alguém já reparou?",
            "Sua maior vergonha na cama?",
            "Quem é a pessoa mais excitada nesta sala?",
            "Qual é o pior relacionamento que você já esteve?",
            "Você já foi despertado no trabalho?",
            "Com que frequência você se masturba? Quantas vezes é sobre mim?",
            "Quanto tempo você fica sem sexo?",
            "Qual é a sua posição sexual menos favorita e por quê?",
            "Você faria um trio? Se você já fez, como foi?",
            "Você já fez sexo lá fora?",
            "Você já depilou seu parceiro?",
            "Que tipo de preliminares você gostaria de experimentar na próxima vez que estivermos na cama?",
            "Que detalhe específico o excita sobre as pessoas que você acha atraentes?",
            "Onde você acha que nosso beijo mais romântico aconteceu?",
            "Quantos namorados (ou namoradas) você já teve?",
            "Você já quis enganar?",
            "Qual é a sua posição sexual menos favorita?",
            "Com que frequência você se masturba? Quantas vezes é sobre mim?",
            "Você prefere as luzes acesas ou apagadas?",
            "Depois de quantas datas você costuma fazer sexo?",
            "Qual foi a sua melhor experiência sexual?",
            "Você prefere abraçar o pós-sexo ou pular no chuveiro?",
            "Como foi seu primeiro beijo?",
            "Você faria sexo por dinheiro?",
            "Você acha que sexo com maquiagem é melhor que sexo cotidiano?",
            "O que mais te excita: assistir pornografia ou gravar uma fita de sexo?",
            "Onde você está no espectro direto / queer? Seja honesto!",
            "Descreva uma cena de sexo de um livro ou filme que realmente o excitou.",
            "Se você é solteiro, sente inveja dos seus amigos em um relacionamento?",
            "Você prefere ser levemente espancado na cama ou ter uma pena suavemente sobre todo o corpo?",
            "Qual foi sua primeira impressão sobre mim?",
            "Nomeie um lugar na casa onde nunca fizemos sexo, mas você gostaria.",
            "Qual foi a coisa mais excêntrica que você já fez?",
            "O que você acha mais quente: sexo em pé contra uma parede ou curvado sobre uma mesa?",
            "Qual a melhor experiência sexual que você já teve?",
            "Digamos que tínhamos um cachecol, um vibrador e uma colher na nossa frente. Diga-me como você usaria cada um em mim.",
            "Qual foi o seu primeiro encontro mais engraçado de todos os tempos?",
            "Se você pudesse voltar e mudar alguma coisa sobre a primeira vez que fizemos sexo, o que seria e por quê?",
            "Você consideraria ser um nudista?",
            "Diga-me uma coisa que eu poderia fazer que faria você imediatamente ter um orgasmo.",
            "O que é algo sujo que você sempre teve vergonha de me dizer na cama?",
            "Qual foi sua primeira emoção sexual?",
            "Você gosta mais quando uso minhas mãos ou meus lábios quando lhe agrada?",
            "Você já ficou em um relacionamento por causa de dinheiro?",
            "O que você acha que é a parte mais sexy do seu corpo?",
            "Você já fez sexo com alguém que conheceu no Tinder?",
            "Compartilhe uma fantasia impertinente que você nunca contou a ninguém.",
            "Qual é a sua parte do corpo favorita em si mesmo? No seu parceiro?",
            "Qual é a música que você mais gosta?",
            "Depois de quantas datas você costuma fazer sexo?",
            "Você já depilou seu parceiro?",
            "Você prefere ter música em segundo plano ou ficar quieta?",
            "Diga-me a zona erógena que você gostaria que eu prestasse mais atenção.",
            "Onde é o seu lugar mais delicado?",
            "Você já pagou por sexo?",
            "Quando foi a última vez que você fez sexo?",
            "Você já fez sexo na cama dos seus pais?",
            "Quando foi sua maior noite de bebedeira?",
            "Qual foi a coisa mais desagradável que você já fez no chuveiro?",
            "Quanto tempo você fica sem sexo?",
            "Em uma escala de um a dez, avalie suas habilidades no quarto. Diga-nos o motivo.",
            "Quanto tempo dura a sua rapidinha ideal?",
            "Qual é a coisa mais aventureira que você gostaria que alguém lhe fizesse?",
            "Qual foi a coisa mais excêntrica que você já fez?",
            "Você prefere receber uma mensagem de texto suja, email ou correio de voz?",
            "Pescoço? Orelha? Mamilo? Em quais partes do corpo você prefere que eu mordisque?",
            "Qual foi a coisa mais estranha que você fez por um namorado ou namorada?",
            "Você prefere brincadeiras onde rimos muito ou sexo apaixonado onde somos muito sensuais?",
            "Quantos namorados (ou namoradas) você já teve?",
            "Qual é o seu lugar favorito para fazer sexo?",
            "Você já foi amigo de alguém? Se sim, por quem?",
            "Qual é o seu 'ponto ideal'?",
            "Qual foi o tempo mais longo que você já deu?",
            "Qual é a música que você mais gosta?",
            "Finja que temos um dia inteiro para passar na cama. Descreva-o em detalhes.",
            "Qual é o pior relacionamento que você já esteve?",
            "Descreva exatamente como é quando você orgasmo.",
            "Qual é a roupa perfeita para você?",
            "Quem foi seu primeiro crush?",
            "Como você se sente sobre sexo em grupos?",
            "Você já fantasiou em fazer sexo com um professor? Se sim, qual?",
            "Você prefere ter música em segundo plano ou ficar quieta?",
            "Você é mais Romeu / Julieta ou Clyde / Bonnie?",
            "Quantas pessoas na sua vida você fez zona de amigos? Nomeie os últimos 3.",
            "Qual é a sua fantasia favorita para se divertir?",
            "Você prefere as luzes acesas ou apagadas?",
            "Há algo que você já viu em um filme cheio de vapor que gostaria de experimentar?",
            "Se você pudesse voltar e mudar alguma coisa sobre a primeira vez que fizemos sexo, o que seria e por quê?",
            "Qual é a sua parte do corpo favorita para eu chupar?",
            "Você prefere dar o primeiro passo no relacionamento ou o seu SO para fazê-lo?",
            "Qual é a sua memória mais romântica?",
            "O que seria mais emocionante: sexo com raiva ou sexo com maquiagem?",
            "Compartilhe uma fantasia impertinente que você nunca contou a ninguém.",
            "Você já pensou em ter uma experiência gay / lésbica?",
            "Você gosta de strip-teases masculinas? Você já viu um antes?",
            "Qual foi a coisa mais desagradável que você já viu online?",
            "Escolha entre US $ 10.000 e seja capaz de atingir facilmente vários orgasmos pelo resto da vida.",
            "Qual é o seu brinquedo sexual favorito para usar em mim?",
            "Qual é o seu tipo de sexo favorito? É macio e doce ou agressivo e travesso?",
            "Qual é o objeto mais louco que você já usou para se apaixonar?",
            "Onde você se sente mais sexy: na pista de dança ou relaxando em um salão escuro e tranquilo?",
            "Você tem uma roupa de 'Estou transando hoje à noite'? O que é isso?",
            "Que figura de autoridade você acha realmente gostosa?",
            "Você gosta de usar lubrificante ou prefere ficar natural?",
        ]
    },
    'Desafio' : {
        'Infantil' : [
            "Brinque de buscar como se você fosse um cachorro.",
            "Atravesse a sala com os olhos vendados sem esbarrar em nada.",
            "Feche os olhos toda vez que alguém falar com você.",
            "Abrace uma árvore por 20 segundos.",
            "Empilhe 5 biscoitos na sua testa.",
            "Dance como um louco com sua música favorita.",
            "Gargalhe como uma bruxa toda vez que você rir.",
            "Dance até o próximo turno.",
            "Faça 10 polichinelos seguidos de 5 flexões.",
            "Faça uma máscara de queijo fatiado.",
            "Finja que você está debaixo d'água pelos próximos 10 minutos.",
            "Faça uma máscara de queijo fatiado.",
            "Diga a promessa de lealdade na voz do seu professor mais odiado.",
            "Faça 10 flexões perfeitas.",
            "Segure um ovo em uma colher o máximo que puder.",
            "Mantenha o dedo na ponta do nariz como se estivesse preso lá.",
            "Gire em círculos por 15 segundos.",
            "Aja como sua mãe quando estiver atrasado para a escola.",
            "Coloque a perna sobre a cabeça.",
            "Quebre um ovo na sua cabeça.",
            "Faça a sua melhor impressão do Mickey Mouse.",
            "Fale com a língua de fora.",
            "Faça malabarismos com ovos.",
            "Jogue um copo de água gelada sobre sua cabeça.",
            "Beba um copo de suco.",
            "Peça a alguém para lhe ensinar como Dougie.",
            "Tente lamber o cotovelo.",
            "Aja como um macaco.",
            "Cante o que você tem a dizer em vez de falar.",
            "Peça o animal de estimação em um quarto em um encontro.",
            "Comece cada frase com 'o que é ...'.",
            "Faça um desenho de (você escolhe) enquanto está com os olhos vendados.",
            "Faça um desenho com os pés.",
            "Coma uma enorme colher de manteiga de amendoim e cante os ABCs.",
            "Franzir a testa por 3 minutos seguidos.",
            "Crie uma história aleatória sobre um objeto à sua direita.",
            "Remova uma meia e um sapato para que um pé fique nu pelo resto do jogo.",
            "Finja que você está debaixo d'água por 10 minutos.",
            "Cante Un Poco Loco.",
            "Mantenha a cara séria por um minuto, enquanto outros tentam fazer você rir.",
            "Fale na terceira pessoa.",
            "Faça o Hokey Pokey sem cantar as palavras.",
            "Faça a macarena silenciosamente até a sua vez novamente.",
            "Tente pegar 3 pequenos pedaços de comida jogados na boca.",
            "Faça o macarena silenciosamente até o próximo turno.",
            "Diga o alfabeto para trás o mais rápido possível.",
            "Use a entrada de automóveis como uma passarela por cinco minutos, enquanto acena o modelo para qualquer carro ou pessoa que esteja passando.",
            "Faça o próximo desafio pela próxima pessoa que receber uma.",
            "Coma uma enorme colher de manteiga de amendoim e cante os ABCs.",
            "Coma um dente de alho.",
        ],
        'Clássico' : [
            "Cante sua canção de ninar favorita em uma voz de bebê.",
            "Mie como um gato até o próximo turno.",
            "Imite um animal escolhido pelo grupo.",
            "Tudo o que você diz para o resto do jogo tem que rimar.",
            "Coma uma colher de maionese.",
            "Fique de quatro e aja como um cachorro até o próximo turno.",
            "Pule na piscina mais próxima. Se não houver, beba um copo de leite.",
            "Seja um cobertor humano (aqueça alguém).",
            "Sussurre por 2 rodadas.",
            "Lamba o cotovelo ou mantenha as mãos sobre a cabeça por 1 turno.",
            "Sapateado por dois minutos do outro lado da sala.",
            "Beije por 5 minutos.",
            "Deixe alguém lamber um círculo completo ao redor do seu rosto.",
            "Abra a janela, incline-se e cante alto o hino nacional.",
            "Vire-se 10 vezes.",
            "A pessoa ao seu lado pode desafiar você.",
            "Faça um backbend.",
            "Beije seu vizinho certo em uma bochecha.",
            "Faça 50 polichinelos.",
            "Leve o jogador à sua esquerda pela sala uma vez.",
            "Gire por 10 segundos e saia da caixa de correio e volte.",
            "Quebre um ovo na sua cabeça.",
            "Cante e toque air guitar com uma música de sua escolha.",
            "Troque de roupa com alguém do sexo oposto e use-a nas próximas quatro rodadas.",
            "Faça um backbend.",
            "Imite Grinch.",
            "Chupe o polegar até que seja a sua vez novamente.",
            "Desista do seu smartphone pelo resto do dia.",
            "Use apenas os cotovelos para criar um status no Facebook e publicá-lo.",
            "Conte uma piada engraçada.",
            "Fique no colo da pessoa à sua direita por 1 turno.",
            "Aja como o animal de estimação da família até a sua vez novamente.",
            "Imite ter um sabre de luz brigando com alguém com barulhos e tudo.",
            "Dê um tiro na pessoa à sua direita.",
            "Faça a girafa.",
            "Tudo o que você diz para o resto do jogo tem que rimar.",
            "Equilibre o objeto à sua esquerda na cabeça pelas próximas três rodadas.",
            "Convide alguém para dançar uma música manca.",
            "Coma um ovo cru.",
            "Levante-se e gire nas próximas duas rodadas.",
            "Coloque uma colher de chá na testa.",
            "Lamber uma maçaneta da porta.",
            "Imite um gato.",
            "Peça permissão na próxima vez em que precisar usar o banheiro.",
            "Faça um backbend.",
            "Sussurro por 2 rodadas.",
            "Amarre as cordas dos seus sapatos e tente caminhar até a porta e para trás.",
            "Escolha qualquer pessoa na sala e cheire seus pés por 10 segundos.",
            "Faça 10 polichinelos e depois faça 10 flexões.",
            "Imite um modelo na passarela.",
            "Cante e toque air guitar com uma música de sua escolha.",
            "Tente fazer seu vizinho rir.",
            "Cante tudo o que você disser pelos próximos 10 minutos.",
            "Faça uma cara de peixe.",
            "Mostre seu umbigo para os jogadores.",
            "Coloque manteiga de amendoim no nariz e tente lambê-lo.",
            "Fique como um flamingo nas próximas quatro rodadas.",
            "Coma um ovo cru.",
            "Coma um pouco de sabão, papel higiênico ou ovo cru.",
            "Faça a dança Macarena.",
        ],
        'Adulto' : [
            "Use um filtro de mudança de voz no Snapchat e envie a alguém uma mensagem dizendo 'Eu quero te chupar até você morrer'.",
            "Use apenas sapatos de salto alto, roupas íntimas e faça uma dança de strip para o grupo.",
            "Descanse as mãos dentro da calça da pessoa ao lado esquerda por 30 segundos.",
            "Use suas calças como uma camisa e sua camisa como suas calças",
            "Vá para os vizinhos e peça emprestado um preservativo.",
            "Encene uma cena sexy de um filme debaixo de um cobertor com outros dois.",
            "Beixe o mamilo do jogador na sua direita.",
            "Cante uma música sexy.",
            "Deixe chupar seu pé.",
            "Você sai da sala e todos escrevem um numero, você volta e escolhe um número, a pessoa com o número tera que te dar um selinho.",
            "Toda vez que você tem que fazer xixi pelo resto da noite, você deve trazer alguém do sexo oposto com você.",
            "Cante uma música sexy.",
            "Compartilhe um pedaço de chiclete com todos sem usar as mãos.",
            "Usar apenas sapatos de salto alto e roupas íntimas faz uma dança de strip para o grupo.",
            "Desembrulhe um pedaço de doce na boca.",
            "Passe levemente as mãos sobre os lábios de outra pessoa e sussurre 'Estou indo, vou' cinco vezes.",
            "Peça a outro jogador para bater em você enquanto faz uma cara sexy até que ele / ela cumpra.",
            "Entre no chuveiro com todas as suas roupas.",
            "Encenar seu pornô favorito.",
            "Escolha alguém para desenhar uma tatuagem na sua bunda.",
            "Passe levemente as mãos sobre os lábios de outra pessoa e sussurre 'Estou indo, vou' cinco vezes.",
            "Todo mundo decide o que sexy atreve a pedir de você.",
            "Lamber a barriga do seu parceiro.",
            "Faça um passeio de dedo na pessoa à sua esquerda.",
            "Vá ao seu vizinho e peça uma banana com uma voz sexy.",
            "Falso ter um orgasmo.",
            "Para um cara: coloque maquiagem. Para uma garota: lave sua maquiagem.",
            "Escolha um jogador, este jogador deve remover uma peça de roupa para cada dose que você bebe.",
            "Mostre ao grupo seus peitos.",
            "Faça 10 polichinelos apenas com roupas íntimas.",
            "Comece a andar e moer a pessoa certa para você.",
            "Vá para os vizinhos e peça emprestado um preservativo.",
            "Puxe seu site pornô favorito no seu telefone agora.",
            "A pessoa à sua direita decide a quem você deve pedir uma data agora.",
            "Deite-se no chão e peça a alguém que finja que está usando giz para desenhar um contorno do seu corpo.",
            "Beije seus dedos.",
            "Faça uma 'dança de espaguete' (cada um leva uma ponta de espaguete seco na boca e dança).",
            "Beije todos os animais de estimação na sala.",
            "Falso ter um orgasmo.",
            "Os franceses beijam o umbigo de uma pessoa.",
            "Estimular duas partes do meu corpo ao mesmo tempo. Use as mãos em uma parte e os lábios na outra.",
            "Na sua voz mais sensual, me diga o que você amou da última vez que fizemos sexo.",
            "Vá ao seu vizinho e peça uma banana com uma voz sexy.",
            "Tire a camisa e faça uma dança do ventre por 30 segundos.",
            "Escolha alguém na sala, essa pessoa escolhe qual peça de roupa você deve remover.",
            "Dê um beijo de 5 segundos para todos os jogadores.",
            "Toque uma música batendo nas nádegas de alguém até que alguém adivinhe a música.",
            "Faça uma massagem nos pés.",
            "Assista a um filme pornô por 3 minutos com o som mudo, você deve dobrar as vozes.",
            "Troque um item de roupa com o jogador à sua direita.",
            "Escolha um jogador, este jogador deve remover uma peça de roupa para cada dose que você bebe.",
            "Dê a alguém que você escolher um chupão no peito.",
            "Deixe que outro jogador lhe dê um chupão em algum lugar do seu corpo.",
            "Chupe o dedo da pessoa à sua direita.",
            "Congele sua cueca por 20 minutos e volte a colocá-la.",
            "Coloque em um show erótico.",
            "Engula um pedaço de chocolate lambido pelo seu parceiro.",
            "Despeje uma trilha de açúcar da parte de baixo das minhas costas no meu pescoço. Agora, lamber.",
            "Componha um poema no local com base em algo que o grupo invente.",
            "Faça uma dança de topless para a pessoa mais distante de você.",
            "Alguém entra na sua conta da Amazon e compra um brinquedo especial para você que custa US $ 20 ou menos.",
            "Deixe o jogador à sua esquerda cortar um pequeno pedaço do seu cabelo.",
            "Twerk por um minuto.",
            "Fale com a mão como se estivesse fazendo um plano de jogo para dormir com outra pessoa que está na sala.",
            "Faça uma impressão do seu parceiro.",
            "Lamber a barriga do seu parceiro.",
            "Faça um strip-tease.",
            "Vou para a outra sala e dou um perfume ou colônia em algum lugar do meu corpo. Você tem que cheirar em todos os lugares até descobrir onde eu o coloco.",
            "Dê a outro jogador uma massagem sensual.",
            "Faça uma provocação em cima da mesa.",
            "Vá até um estranho bem de sua escolha e peça um beijo.",
            "Mime a ação que você gostaria que seu parceiro fizesse com você.",
            "Faça uma ligação para uma pessoa com quem o grupo concorda. Tente convencê-los a fazer sexo com você.",
            "O grupo decide para quem você liga, você deve tentar convencê-los a fazer sexo com você.",
            "Venda um amigo e faça com que ele beije três objetos. Apenas não diga a eles o que são.",
            "Use suas calças como uma camisa e sua camisa como suas calças. As meias ficam nas suas mãos e correm por 30 segundos.",
            "Coloque meu celular vibrando e coloque-o em algum lugar do meu corpo. Agora me liga.",
            "Dê a alguém um 'beijo de tia'. Peça um batom e dê um beijo.",
            "Sussurre o nome do seu parceiro de uma maneira sexy.",
            "Entre na sala ao lado e faça um vídeo de sexo com seu parceiro por 5 minutos.",
            "Lamba a pessoa à sua esquerda, do pescoço até a borda da cueca.",
            "Escolha uma vítima que você irá provocar pelos próximos 5 minutos.",
            "Coma um pedaço de fruta da cueca do seu parceiro.",
            "Cite alguém que você acha que sairá mais tarde na vida.",
            "Faça uma massagem no pescoço para a pessoa mais próxima do sexo oposto.",
            "Deixe alguém lhe dar uma mamadeira.",
            "Faça uma dança de topless para a pessoa mais distante de você.",
            "Deite-se no chão e peça a alguém que finja que está usando giz para desenhar um contorno do seu corpo.",
            "Faça um número impressionante de strip-tease com todos os acessórios que encontrar - basta fazê-lo funcionar.",
            "Finja que sou um estranho em um bar. Tente me pegar e me convencer a voltar para casa com você.",
        ]
    },
}

export default dados;
